// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bigdata.proto

#ifndef PROTOBUF_bigdata_2eproto__INCLUDED
#define PROTOBUF_bigdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class obj_big_data;
class obj_big_dataDefaultTypeInternal;
extern obj_big_dataDefaultTypeInternal _obj_big_data_default_instance_;

namespace protobuf_bigdata_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_bigdata_2eproto

// ===================================================================

class obj_big_data : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:obj_big_data) */ {
 public:
  obj_big_data();
  virtual ~obj_big_data();

  obj_big_data(const obj_big_data& from);

  inline obj_big_data& operator=(const obj_big_data& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const obj_big_data& default_instance();

  static inline const obj_big_data* internal_default_instance() {
    return reinterpret_cast<const obj_big_data*>(
               &_obj_big_data_default_instance_);
  }

  void Swap(obj_big_data* other);

  // implements Message ----------------------------------------------

  inline obj_big_data* New() const PROTOBUF_FINAL { return New(NULL); }

  obj_big_data* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const obj_big_data& from);
  void MergeFrom(const obj_big_data& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(obj_big_data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 records = 1;
  int records_size() const;
  void clear_records();
  static const int kRecordsFieldNumber = 1;
  ::google::protobuf::int64 records(int index) const;
  void set_records(int index, ::google::protobuf::int64 value);
  void add_records(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      records() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_records();

  // @@protoc_insertion_point(class_scope:obj_big_data)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > records_;
  mutable int _records_cached_byte_size_;
  mutable int _cached_size_;
  friend struct  protobuf_bigdata_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// obj_big_data

// repeated int64 records = 1;
inline int obj_big_data::records_size() const {
  return records_.size();
}
inline void obj_big_data::clear_records() {
  records_.Clear();
}
inline ::google::protobuf::int64 obj_big_data::records(int index) const {
  // @@protoc_insertion_point(field_get:obj_big_data.records)
  return records_.Get(index);
}
inline void obj_big_data::set_records(int index, ::google::protobuf::int64 value) {
  records_.Set(index, value);
  // @@protoc_insertion_point(field_set:obj_big_data.records)
}
inline void obj_big_data::add_records(::google::protobuf::int64 value) {
  records_.Add(value);
  // @@protoc_insertion_point(field_add:obj_big_data.records)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
obj_big_data::records() const {
  // @@protoc_insertion_point(field_list:obj_big_data.records)
  return records_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
obj_big_data::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:obj_big_data.records)
  return &records_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bigdata_2eproto__INCLUDED
