

#INCLUDE(${CMAKE_HOME_DIRECTORY}/cmake/FindVcpkg.cmake)

#[[
MESSAGE(STATUS "debug release CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE}")
MESSAGE(STATUS "debug release CMAKE_C_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG}")
MESSAGE(STATUS "debug release CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELEASE}")
MESSAGE(STATUS "debug release CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG}")
MESSAGE(STATUS "debug release CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE}")
#]]

## include
SET(BOOST_INCLUDE_DIR ${VCPKG_ROOT_INCLUDE_DIR})
FIND_PATH(BOOST_INCLUDE_PATH boost/utility.hpp
        PATHS
        ${BOOST_INCLUDE_DIR}
        
        NO_DEFAULT_PATH
    )
IF(NOT BOOST_INCLUDE_PATH)
    MESSAGE(FATAL_ERROR "Can't find BOOST_INCLUDE_PATH: ${BOOST_INCLUDE_PATH}")
ELSE()
    #MESSAGE(STATUS "Set BOOST_INCLUDE_PATH: ${BOOST_INCLUDE_PATH}")
ENDIF()


## 设置library 目录 boost .lib/.so
IF(WIN32)
    SET(BOOST_LIBRARY_DIR ${VCPKG_ROOT_DIR}\\debug\\lib)
ELSEIF(UNIX)
    SET(BOOST_LIBRARY_DIR "/usr/local/lib")
ENDIF(WIN32)

## boost .lib 命名规则
IF(WIN32)
    SET(BOOST_LIB_PREFIX "")
    SET(BOOST_LIB_POSTFIX "-vc140-mt-gd.lib")
ELSE(UNIX)
    SET(BOOST_LIB_PREFIX "lib")
    SET(BOOST_LIB_POSTFIX ".so")
ENDIF()
MESSAGE("boost libraries name rule: ${BOOST_LIB_PREFIX}boost_xxx${BOOST_LIB_POSTFIX}")


## 添加需要的boost libraries
SET(BOOST_LIBRARIES_LIST boost_program_options boost_log boost_thread boost_date_time boost_filesystem boost_system)

#SET(BOOST_LIBRARIES ""   CACHE STRING "boost libraries")
FOREACH(LIB_NAME ${BOOST_LIBRARIES_LIST})
    SET(BOOST_LIB_NAME "${BOOST_LIB_PREFIX}${LIB_NAME}${BOOST_LIB_POSTFIX}")
    FIND_LIBRARY(${LIB_NAME}_PATH ${BOOST_LIB_NAME} PATHS ${BOOST_LIBRARY_DIR})
    IF(NOT BOOST_LIB_NAME)
        MESSAGE(FATAL_ERROR "Can't find  ${BOOST_LIB_NAME} ${BOOST_LIBRARY_DIR}")
    ELSE()
        #MESSAGE("find boost lib: ${${LIB_NAME}_PATH} ${BOOST_LIB_NAME}")
    ENDIF()
    SET(BOOST_LIBRARIES ${BOOST_LIBRARIES} ${${LIB_NAME}_PATH})
ENDFOREACH()



MESSAGE(STATUS "BOOST_INCLUDE_DIR: ${BOOST_INCLUDE_DIR}")
MESSAGE(STATUS "BOOST_LIBRARY_DIR: ${BOOST_LIBRARY_DIR}")
MESSAGE(STATUS "BOOST_LIBRARIES: ${BOOST_LIBRARIES}")

