


SET(MYSQL_INCLUDE_DIR ${VCPKG_ROOT_INCLUDE_DIR}\\mysql
    #CACHE STRING "mysql include"
)
IF(NOT MYSQL_INCLUDE_DIR)
    MESSAGE(FATAL_ERROR "Can't find MYSQL_INCLUDE_DIR: ${MYSQL_INCLUDE_DIR}")
ELSE()
    #MESSAGE(STATUS "Set MYSQL_INCLUDE_DIR: ${MYSQL_INCLUDE_DIR}")
ENDIF()



## mysql library 目录
IF(WIN32)
    SET(MYSQL_LIBRARY_DIR ${VCPKG_ROOT_DIR}\\debug\\lib)
ELSEIF(UNIX)
    SET(MYSQL_LIBRARY_DIR "/usr/local/lib")
ENDIF(WIN32)

IF(NOT MYSQL_LIBRARY_DIR)
    MESSAGE(FATAL_ERROR "Can't find MYSQL_LIBRARY_DIR: ${MYSQL_LIBRARY_DIR}")
  ELSE()
    #MESSAGE(STATUS "Set MYSQL_LIBRARY_DIR: ${MYSQL_LIBRARY_DIR}")
ENDIF()


## 添加需要的 libraries
FIND_LIBRARY(MYSQLCLIENT_LIBRARY_DIR libmysql.lib PATHS ${MYSQL_LIBRARY_DIR})
IF(NOT MYSQLCLIENT_LIBRARY_DIR)
    MESSAGE(FATAL_ERROR "Can't find  ${MYSQLCLIENT_LIBRARY_DIR} ${MYSQLCLIENT_LIBRARY_DIR}")
ELSE()
    #MESSAGE("find boost lib: ${${LIB_NAME}_PATH} ${BOOST_LIB_NAME}")
    
ENDIF()

SET(MYSQL_LIBRARIES ${MYSQL_LIBRARIES} ${MYSQLCLIENT_LIBRARY_DIR})

MESSAGE(STATUS "MYSQL_INCLUDE_DIR: ${MYSQL_INCLUDE_DIR}")
MESSAGE(STATUS "MYSQL_LIBRARY_DIR: ${MYSQL_LIBRARY_DIR}")
MESSAGE(STATUS "MYSQL_LIBRARIES: ${MYSQL_LIBRARIES}")

